"""Generate the auditable Phase 2 LaTeX fragment from its locked JSON summary."""

import argparse
import json
import statistics
from pathlib import Path


def estimate(rows, key):
    values = [float(row[key]) for row in rows]
    return statistics.mean(values), statistics.stdev(values) if len(values) > 1 else 0.0


def format_estimate(rows, key):
    mean, deviation = estimate(rows, key)
    return f"{mean:.3f} $\\pm$ {deviation:.3f}"


def generate(summary):
    lines = [
        "% Generated by scripts/export_phase2_report.py; do not hand-edit.",
        "\\newcommand{\\PhaseTwoStatus}{Phase 2 confirmatory gate: FAILED}",
        "\\begin{table*}[t]",
        "\\centering",
        "\\scriptsize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{lccccc}",
        "\\toprule",
        "Method & Seeds & Abstract & Profiles & Grid AUC & Cooperation \\\\",
        "\\midrule",
    ]
    for method in ["mappo_nominal", "mappo_uniform_dr", "mappo_failure_dr"]:
        record = summary["methods"][method]
        rows = record["per_seed"]
        lines.append(
            f"{record['display_name']} & {len(rows)} & "
            f"{format_estimate(rows, 'abstract_intercept_success')} & "
            f"{format_estimate(rows, 'profile_mean_success')} & "
            f"{format_estimate(rows, 'grid_auc')} & "
            f"{format_estimate(rows, 'cooperative_success')} \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\caption{Phase 2 confirmatory seed-level means $\\pm$ sample standard deviations. "
            "Each entry first reduces an evaluation suite to one value per independently trained "
            "actor; unlike suites and episode replicates are never treated as training seeds.}",
            "\\label{tab:phase2-confirmatory}",
            "\\end{table*}",
            "",
            "\\begin{table*}[t]",
            "\\centering",
            "\\small",
            "\\begin{tabular}{p{0.22\\textwidth}p{0.58\\textwidth}c}",
            "\\toprule Gate & Locked criterion & Result \\\\",
            "\\midrule",
        ]
    )
    labels = [
        ("minimum_training_seeds", "Independent seeds"),
        ("profile_mean_advantage", "Profile advantage"),
        ("profile_direction_stability", "Direction stability"),
        ("grid_noninferiority", "Delay--noise non-inferiority"),
        ("abstract_intercept_noninferiority", "Nominal competence"),
        ("cooperation", "Learned cooperation"),
    ]
    for key, label in labels:
        gate = summary["gates"][key]
        result = "PASS" if gate["passed"] else "FAIL"
        lines.append(f"{label} & {gate['criterion']} & {result} \\\\")
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\caption{Locked Phase 2 decision checks. The overall decision is failure if any "
            "required scientific check fails; passing the robustness checks cannot compensate "
            "for loss of nominal competence or absent team play.}",
            "\\label{tab:phase2-gates}",
            "\\end{table*}",
            "",
        ]
    )
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--summary", default="reports/phase2_confirmatory_summary.json")
    parser.add_argument("--output", default="reports/generated_results.tex")
    args = parser.parse_args()
    summary = json.loads(Path(args.summary).read_text(encoding="utf-8"))
    Path(args.output).write_text(generate(summary), encoding="utf-8")
    print(args.output)


if __name__ == "__main__":
    main()
